#!bin/bash

echo "Apply database migrations"
python3.8 manage.py migrate

echo "Configuring static files"
echo "yes" | python3.8 manage.py collectstatic

echo "Create superuser"
echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'ubiwherepwd')" | python3.8 manage.py shell

echo Starting gunicorn
exec gunicorn --bind 0.0.0.0:8000 --workers 2 --timeout=1200 ubiwhereproject.wsgi

