# Generated by Django 3.0.7 on 2020-06-15 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[('SPECIAL_EVENT', 'Special Event'), ('INDICENT', 'Incident'), ('WEATHER_CONDITION', 'Weather Condition'), ('ROAD_CONDITION', 'Road Condition')], max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Occurrences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1200)),
                ('address', models.CharField(max_length=1200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('VERIFYING', 'Verifying'), ('VALIDATED', 'Validated'), ('RESOLVED', 'Resolved')], max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='occurrences.Category')),
            ],
        ),
    ]
