# Generated by Django 3.0.7 on 2020-06-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0002_auto_20200616_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrences',
            name='category',
            field=models.CharField(choices=[('SPECIAL_EVENT', 'Special Event'), ('INCIDENT', 'Incident'), ('WEATHER_CONDITION', 'Weather Condition'), ('ROAD_CONDITION', 'Road Condition')], max_length=500),
        ),
    ]
