# Generated by Django 3.0.7 on 2020-06-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0003_auto_20200616_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrences',
            name='address',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
